trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'keyvault-connection'
    KeyVaultName: 'myvault98600'
    SecretsFilter: 'dbpassword'

- script: |
    mkdir output
    echo "Secret successfully retrieved from Azure Key Vault" > output/result.txt
  displayName: Create Output File

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'output'
    artifact: 'newfeed'
  displayName: Publish Artifact